#!/bin/bash

echo "================================"
echo "Free Domain Options for OAuth"
echo "================================"
echo ""
echo "Option A: Use DuckDNS (Recommended)"
echo "1. Go to https://www.duckdns.org/"
echo "2. Sign in with Google/GitHub"
echo "3. Create subdomain like: vanguard-insurance.duckdns.org"
echo "4. Point it to: 162.220.14.239"
echo "5. Use in OAuth: http://vanguard-insurance.duckdns.org/api/gmail/callback"
echo ""
echo "Option B: Use No-IP"
echo "1. Go to https://www.noip.com/"
echo "2. Create free account"
echo "3. Create hostname like: vanguard.hopto.org"
echo "4. Point to: 162.220.14.239"
echo ""
echo "Option C: Use nip.io (Instant, no signup)"
echo "1. Use: 162-220-14-239.nip.io"
echo "2. It automatically resolves to 162.220.14.239"
echo "3. OAuth URI: http://162-220-14-239.nip.io/api/gmail/callback"
echo ""
echo "================================"
