#!/bin/bash
echo "================================"
echo "Gmail OAuth Setup"
echo "================================"
echo ""
echo "✅ Domain configured: http://162-220-14-239.nip.io"
echo ""
echo "In Google Cloud Console, use:"
echo "Redirect URI: http://162-220-14-239.nip.io/api/gmail/callback"
echo ""
echo "To update credentials, edit .env file:"
echo "  nano /var/www/vanguard/.env"
echo ""
echo "Replace:"
echo "  GMAIL_CLIENT_ID=your-actual-client-id"
echo "  GMAIL_CLIENT_SECRET=your-actual-client-secret"
echo ""
echo "Then restart: pm2 restart all"
echo "================================"
