#!/bin/bash

echo "================================"
echo "Localhost Testing Setup for Gmail OAuth"
echo "================================"
echo ""
echo "Since Google requires a domain (not IP) for OAuth,"
echo "you can test using SSH tunneling:"
echo ""
echo "1. On your LOCAL computer, run:"
echo "   ssh -L 3001:localhost:3001 -L 8897:localhost:8897 corp06@162.220.14.239"
echo ""
echo "2. In Google Cloud Console, use this redirect URI:"
echo "   http://localhost:3001/api/gmail/callback"
echo ""
echo "3. Access the application at:"
echo "   http://localhost:3001"
echo ""
echo "4. Update .env file with:"
echo "   GMAIL_REDIRECT_URI=http://localhost:3001/api/gmail/callback"
echo ""
echo "================================"
echo "For production, you'll need a real domain name."
echo "================================"
