#!/bin/bash

echo "=================================================="
echo "GitHub Repository Push Script"
echo "=================================================="
echo ""
echo "This script will help you push the changes to GitHub."
echo ""
echo "Current Git Status:"
echo "------------------"
git status --short
echo ""
echo "Last Commit:"
echo "-----------"
git log -1 --oneline
echo ""
echo "=================================================="
echo ""
echo "To push to GitHub, you need to authenticate first."
echo ""
echo "Option 1: Use GitHub CLI (Recommended)"
echo "----------------------------------------"
echo "Run: gh auth login"
echo "Then run: git push -u origin main"
echo ""
echo "Option 2: Use HTTPS with Personal Access Token"
echo "-----------------------------------------------"
echo "1. Generate a token at: https://github.com/settings/tokens"
echo "2. Run: git remote set-url origin https://USERNAME:TOKEN@github.com/Corptech02/VIG-Software-Most-Recent-.git"
echo "3. Run: git push -u origin main"
echo ""
echo "Option 3: Use SSH"
echo "------------------"
echo "1. Add SSH key to GitHub: https://github.com/settings/keys"
echo "2. Run: git remote set-url origin git@github.com:Corptech02/VIG-Software-Most-Recent-.git"
echo "3. Run: git push -u origin main"
echo ""
echo "=================================================="
echo ""
echo "Repository URL: https://github.com/Corptech02/VIG-Software-Most-Recent-"
echo "Local branch: main"
echo "Files committed: $(git diff --stat HEAD^ HEAD 2>/dev/null | tail -1 | cut -d' ' -f2) files changed"
echo ""