#!/bin/bash

echo "======================================"
echo "QUICK GMAIL SETUP FOR COI SYSTEM"
echo "======================================"
echo ""
echo "1. Create a Gmail account (or use existing one)"
echo "2. Go to: https://myaccount.google.com/apppasswords"
echo "3. Create an app password for 'Mail'"
echo "4. Update the .env file:"
echo ""
echo "Edit: /var/www/vanguard/backend/.env"
echo "Change to:"
echo "  OUTLOOK_EMAIL=your-email@gmail.com"
echo "  OUTLOOK_PASSWORD=your-app-password"
echo "  OUTLOOK_IMAP_HOST=imap.gmail.com"
echo "  OUTLOOK_IMAP_PORT=993"
echo "  OUTLOOK_SMTP_HOST=smtp.gmail.com"
echo "  OUTLOOK_SMTP_PORT=587"
echo ""
echo "5. Run: pm2 restart vanguard-backend"
echo ""
echo "This will work immediately with Gmail!"
echo "======================================"